<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect(array(
    'image',
    'name',
    'short_description'
))
    ->addFieldToFilter('visibility', array(
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
    )) //showing just products visible in catalog or both search and catalog
    ->addFinalPrice()
    ->getSelect()
    ->where('price_index.final_price < price_index.price')
                        ->limit(2) //we can specify how many products we want to show on this page
;

Mage::getModel('review/review')->appendSummary($_productCollection);

$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="dropdown-menu">
        <ul>
            <li class="item display-list hot-deals group" style="width:25%">
                <span class="menu-title"><?php echo $this->__('New products');?></span>
            </li>
            <li class="item display-list hot-deals group" style="width:25%">
                <span class="menu-title"><?php echo $this->__('Special products');?></span>
                <div class="block_content">

                   <ul class="products_block row">
                       <?php foreach ($_productCollection as $_product): ?>
                       <li class="ajax_block_product product_block  col-xs-12 col-sm-6 col-md-6 first_item">

                           <div class="product-container style1 clearfix">
                               <?php // Product Image ?>
                               <div class="left-block">
                                   <div class="product-image-container">
                                       <div class="vel-image-more" data-idproduct="8">
                                           <a href="<?php echo $_product->getProductUrl() ?>" data-fancybox-group="other-views" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                               <img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="image" >
                                           </a>
                                       </div>
                                       <a class="product_img_link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="url">
                                           <img class=" img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="image">
                                       </a>
                                   </div>

                               </div>
                               <?php // Product description ?>
                               <div class="right-block">
                                   <div class="f-fix">
                                       <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                       <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                       <?php if($_product->getRatingSummary()): ?>
                                           <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                       <?php endif; ?>
                                   </div>
                               </div>
                           </div>

                        </li>
                       <?php endforeach; ?>
                   </ul>
                </div>
            </li>
            <li class="item display-list hot-deals group" style="width:25%">
                <span class="menu-title"><?php echo $this->__('bestseller products');?></span>
            </li>
            <li class="item display-list hot-deals group" style="width:25%">
                <span class="menu-title"><?php echo $this->__('Featured products');?></span>
                <div class="block_content">

                    <ul class="products_block row">
                        <?php foreach ($_productCollection as $_product): ?>
                            <li class="ajax_block_product product_block  col-xs-12 col-sm-6 col-md-6 first_item">

                                <div class="product-container style1 clearfix">
                                    <?php // Product Image ?>
                                    <div class="left-block">
                                        <div class="product-image-container">
                                            <div class="vel-image-more" data-idproduct="8">
                                                <a href="<?php echo $_product->getProductUrl() ?>" data-fancybox-group="other-views" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                                    <img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="image" >
                                                </a>
                                            </div>
                                            <a class="product_img_link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="url">
                                                <img class=" img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="image">
                                            </a>
                                        </div>

                                    </div>
                                    <?php // Product description ?>
                                    <div class="right-block">
                                        <div class="f-fix">
                                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                            <?php if($_product->getRatingSummary()): ?>
                                                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>

                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </li>
            <li class="item  group" style="width:100%"><div class="menu-content"><p><img class="img-responsive" src="http://velatheme.com/demo/elise_multi/vel_supershop/modules/velmegamenu/image/banner-menu.jpg" alt=""></p></div></li>
        </ul>
    </div>
<?php endif; ?>
<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage_browse_categories')->toHtml() ?>
