<div class="dropdown-menu">
    <ul>
        <li class="item group" style="width:25%"><a href="http://velatheme.com/demo/elise_multi/vel_elise/en/1-root" title="Clothing">Clothing</a><div class="dropdown-menu"><ul><li class="item "><a href="http://velatheme.com/demo/elise_multi/vel_elise/en/1-root" title="Coats &amp; Jackets">Coats &amp; Jackets</a></li>
                    <li class="item "><a href="#" title="Dresses">Dresses</a></li>
                    <li class="item "><a href="#" title="Jeans">Jeans</a></li>
                    <li class="item "><a href="#" title="Sportswear &amp; Joggers">Sportswear &amp; Joggers</a></li>
                    <li class="item "><a href="#" title="Swim &amp; Beachwear">Swim &amp; Beachwear</a></li>
                </ul></div></li>
        <li class="item group" style="width:25%"><a href="#" title="Clothing">Clothing</a><div class="dropdown-menu"><ul><li class="item "><a href="#" title="Coats &amp; Jackets">Coats &amp; Jackets</a></li>
                    <li class="item "><a href="#" title="Coats &amp; Jackets">Coats &amp; Jackets</a></li>
                    <li class="item "><a href="#" title="Dresses">Dresses</a></li>
                    <li class="item "><a href="#" title="Jeans">Jeans</a></li>
                    <li class="item "><a href="#" title="Sportswear &amp; Joggers">Sportswear &amp; Joggers</a></li>
                    <li class="item "><a href="#" title="Swim &amp; Beachwear">Swim &amp; Beachwear</a></li>
                </ul></div></li>
        <li class="item group" style="width:25%"><a href="#" title="Clothing">Clothing</a><div class="dropdown-menu"><ul><li class="item "><a href="#" title="Coats &amp; Jackets">Coats &amp; Jackets</a></li>
                    <li class="item "><a href="#" title="Dresses">Dresses</a></li>
                    <li class="item "><a href="#" title="Jeans">Jeans</a></li>
                    <li class="item "><a href="#" title="Sportswear &amp; Joggers">Sportswear &amp; Joggers</a></li>
                    <li class="item "><a href="#" title="Swim &amp; Beachwear">Swim &amp; Beachwear</a></li>
                </ul></div></li>
        <li class="item  group" style="width:25%"><span class="menu-title">Custom html</span><div class="menu-content"><p><img class="img-responsive" src="http://velatheme.com/demo/elise_multi/vel_supershop/modules/velmegamenu/image/banner.jpg" alt=""></p></div></li>
    </ul>
</div>