<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect(array(
        'image',
        'name',
        'short_description'
    ))
    ->addFieldToFilter('visibility', array(
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
    )) //showing just products visible in catalog or both search and catalog
    ->addFinalPrice()
//                        ->addAttributeToSort('price', 'asc') //in case we would like to sort products by price
    ->getSelect()
    ->where('price_index.final_price < price_index.price')
//                        ->limit(30) //we can specify how many products we want to show on this page
//                        ->order(new Zend_Db_Expr('RAND()')) //in case we would like to sort products randomly
;

Mage::getModel('review/review')->appendSummary($_productCollection);

$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="products_block col-md-6 col-sm-6 col-xs-12 hot-deals  margin-40 col-sm-12  col-xs-12">
        <div class="block products-carousel">
            <h4 class="title_block">
                <span><?php echo $this->__('HOT DEALS');?></span>
            </h4>
        <?php $_iterator = 0; ?>
        <div class="block_content">
            <div id="productlist-sale" class="product_list grid">

            <?php foreach ($_productCollection as $_product): ?>
                <div class="owl-item item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                    <div class="ajax_block_product product_block">
                    <div class="product-container default clearfix">
                    <?php // Product Image ?>
                         <div class="left-block">
                             <div class="product-image-container">
                                 <div class="vel-image-more" data-idproduct="8">
                                     <a href="<?php echo $_product->getProductUrl() ?>" data-fancybox-group="other-views" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                         <img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="image" >
                                     </a>
                                 </div>
                                 <a class="product_img_link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="url">
                                     <img class=" img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="image">
                                 </a>
                             </div>
                             <a class="quick-view" href="<?php echo $_product->getProductUrl() ?>" title="Quick view">
                                 <i class="icon icon-eye-open"></i>
                                 <span>Quick view</span>
                             </a>
                         </div>
                         <?php // Product description ?>
                    <div class="right-block">
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                            <?php if($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                            <?php endif; ?>
                            <div class="content_price"> <?php echo $this->getPriceHtml($_product, true) ?></div>
                            <p class="product-desc">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            </p>
                            <div class="functional-buttons clearfix">
                                <?php if($_product->isSaleable()): ?>
                                    <div class="addtocart">
                                        <a title="<?php echo $this->__('Add to Cart') ?>" class="ajax_add_to_cart_button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                            <i class="icon icon-shopping-cart"></i>
                                            <span><?php echo $this->__('Add to Cart') ?></span>
                                        </a>
                                    </div>
                                <?php else: ?>
                                    <div class="addtocart"> <span><?php echo $this->__('Out of stock') ?></span></div>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <a href="<?php echo $_compareUrl ?>" class="add_to_compare">
                                        <i class="icon icon-copy"></i>
                                        <span><?php echo $this->__('Compare') ?></span>
                                    </a>
                                <?php endif; ?>
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="addToWishlist">
                                        <i class="icon icon-heart-empty"></i>
                                        <span><?php echo $this->__('Wishlist') ?></span>
                                    </a>
                                <?php endif; ?>
                            </div>
                    </div>
                    </div>
                    </div>
                </div>
            <?php endforeach; ?>
               </div>
            </div>
        </div>
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    </div>
<?php endif; ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage_browse_categories')->toHtml() ?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#productlist-sale').owlCarousel({
            items:1,
            loop:true,
            autoWidth:true,
            stagePadding: 100,
            navigation:true
        });

        jQuery('.quick-view').click(function(e){
            e.preventDefault();
            var url = jQuery(this).attr('href');
            if (url.indexOf('?') != -1)
                url += '&';
            else
                url += '?';
            jQuery.fancybox({
                'padding':  0,
                'width':    1087,
                'height':   610,
                'type':     'iframe',
                'href':     url + 'content_only=1'
            });
        });

    });
</script>