
<?php
$display_from_date = Mage::getStoreConfig("countdown/date_promotions/from_date");

$display_to_date = Mage::getStoreConfig("countdown/date_promotions/to_date");
//========== config in admin : date display countdown promotions popup
$display_date = Mage::getModel('core/date')->date('Y-m-d');
$three_day_ago = Mage::getModel('core/date')->date('Y-m-d', strtotime('-3 day'));
$three_day_feature = Mage::getModel('core/date')->date('Y-m-d', strtotime('+3 day'));
$before_one_day = Mage::getModel('core/date')->date('Y-m-d', strtotime('-1 day'));
$after_one_day = Mage::getModel('core/date')->date('Y-m-d', strtotime('+1 day'));

//========= date for filter collection countdown products.
$date = strtotime($display_to_date); // count to countdown
//========== date for count down
if( !empty($display_from_date) && !empty($display_to_date) &&
    strtotime($display_from_date) <= strtotime($display_date)
    && strtotime($display_date) <= strtotime($display_to_date)) {
//============ display popup from $display_from_date to $display_to_date.
?>
<div id="countdown-promotion-popup" class="count-down-countdown-promo" style="display: none">
<?php    if($date){
        $year = date("Y",$date);
        $month = date("m",$date);
        $day = date("d",$date);
        $hour = date("H",$date);
        $minute = date("i",$date);
        ?>
        <div class="countdown-promotions">
        <div class="countdown-promotions-top">
            <div class="count-down">
                <script type="text/javascript">
                    var Countdown<?php echo rand(100,999); ?> = new Countdown({
                        year	: <?php echo $year; ?>,
                        month	: <?php echo $month; ?>,
                        day	: <?php echo $day; ?>,
                        hour	: <?php echo $hour; ?>,
                        minute	: <?php echo $minute; ?>,
                        second	: 0,
                        width:'450',
                        height:'100',
                        color	: "#FFFFFF",
                        style:"flip",
                        rangeHi: "day"
                    });
                </script>
            </div>
        </div>
    <?php } ?>
    <?php $checkDate = null;$checkDate2 = null;$checkDate3 = null;
    $currency = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
    ?>
    <?php
    $_products_three_day_before = Mage::getModel('catalog/product')->getCollection()
        ->addFieldToFilter('countdown_promo',array('lteq'=>$before_one_day))
        ->addFieldToFilter('countdown_promo',array('gteq'=>$three_day_ago))
        ->addAttributeToSort('countdown_promo', 'asc')
        ->addAttributeToSelect('image');
    $_products_current = Mage::getModel('catalog/product')->getCollection()
        ->addFieldToFilter('countdown_promo',array('eq'=>$display_date))
        ->addAttributeToSelect('name')
        ->addAttributeToSelect('price')
        ->addAttributeToSelect('image');
    ?>
    <div class="widget widget-countdown-products">
        <div class="widget-products-countdown-promotions">
            <ul class="countdown-product-list-ago">
                <?php foreach ($_products_three_day_before as $_product): ?>
                    <?php if(strtotime($checkDate) != strtotime($_product->getCountdownPromo())):?>
                        <li class="item" >
                            <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                            <div class="aldigridproductouterbox">
                                <div class="image-box-countdown">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(100,125); ?>" width="100" height="100" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                                    </a>
                                </div>
                                <div class="date-countdown">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                                        <?php echo date('d', strtotime($_product->getCountdownPromo()));?>
                                    </a>
                                </div>
                            </div>
                        </li>
                        <?php $checkDate = $_product->getCountdownPromo(); ?>
                    <?php endif;?>
                <?php endforeach;?>
            </ul>
            <ul class="countdown-product-current">
                <?php foreach ($_products_current as $_product): ?>
                    <?php if(strtotime($checkDate2) != strtotime($_product->getCountdownPromo())):?>
                        <li class="item" >
                            <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                            <div class="aldigridproductouterbox">
                                <div class="image-box-countdown">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(326); ?>" width="100" height="100" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                                    </a>
                                </div>
                                <div class="product-price-current-date">
                                    <?php $price = floatval($_product->getPrice());
                                    list($whole, $decimal) = explode('.', $price);
                                    if($decimal==0) $decimal ='00';
                                    ?>
                                    <span><span class="price-current"><?php echo $currency.$whole;?></span><sup><?php echo '.'.$decimal;?></sup></span>

                                </div>
                                <div class="countdown-buynow">
                                    <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                                        <span><?php echo $this->__('View detail');?></span>
                                    </a>
                                </div>
                                <div class="countdown-detail-product">
                                    <h3 class="product-name">
                                        <a href="<?php echo $_product->getProductUrl() ?>"
                                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                            <?php echo $_product->getName();?>
                                        </a>
                                    </h3>
                                </div>
                            </div>
                        </li>
                        <?php $checkDate2 = $_product->getCountdownPromo(); ?>
                    <?php endif;?>
                <?php endforeach;?>
            </ul>

        </div>
    </div>
    </div>

    <script type="text/javascript">

        if(!Mage.Cookies.get('countdown')){
            // cookie not set
            Mage.Cookies.set('countdown', 'now');
            var show = true;
            //console.log('setting cookie : '+show);
        }else{
            ///cookie is set!
            var show = false;
        }
        //});

    </script>
    <script type="text/javascript">
        function getQueryParams(qs) {
            qs = qs.split("+").join(" ");
            var params = {},
                tokens,
                re = /[?&]?([^=]+)=([^&]*)/g;

            while (tokens = re.exec(qs)) {
                params[decodeURIComponent(tokens[1])] = decodeURIComponent(tokens[2]);
            }

            return params;
        }

        var $_GET = getQueryParams(document.location.search);

        jQuery(document).ready(function(){
            var loaded = false;
            if( jQuery(window).width() < 1200) var width = '100%';
            else if( jQuery(window).width()> 1899) var  width = '51,9%';
            else var width = '72%';
            if(show || $_GET['countdown']){
                jQuery("#click-countdown-popup").fancybox({
                    padding: 0,
                    hideOnContentClick: true,
                    closeBtn : true,
                    autoCenter: false,
                    autoSize: false,
                    width: '960px',
                    openEffect  : 'none',
                    afterLoad: function () {
                        jQuery(".fancybox-wrap").addClass("christmas-promotions-content");
                    },
                    onUpdate: function() {
                        leftVal = jQuery( window ).width() - jQuery(".fancybox-wrap").width();
                        leftVal = leftVal/2;
                        jQuery(".fancybox-wrap").css('left', leftVal + 'px');
                    },
                    closeEffect : 'none'
                });
            }
            jQuery("#click-countdown-popup").trigger('click');

        });

    </script>
</div>
<a href="#countdown-promotion-popup" id="click-countdown-popup" style="display: none">click</a>
<?php } ?> <!--end check from date and to date -->
